---
title: "Capstone Graphs"
author: "ShaNiece Twitty"
date: "2025-03-26"
output: pdf_document
---

```{r setup, include=FALSE}
library(HousingMarket)
library(tidyverse)
library(paletteer)
library(viridis)
library(paletteer)
HousingMarket$Month.of.Period.End <- ym(HousingMarket$Month.of.Period.End)
```



```{r cars}
ggplot(HousingMarket , aes(x = Month.of.Period.End , y = Average.Sale.To.List , color = Region, group = Region)) +
    geom_point(size = 2, alpha = 0.7) +
    geom_line(size = 1, alpha = 0.8) +
  scale_color_viridis_d(option = "C",begin =0.1, end = 0.9)+
    labs(
      title = "Housing sale Discrepancy",
      x = "Year",
      y = "Average Sale To List Each Month",
      color = "Region"
    ) +
  scale_x_date(date_labels = " %Y", date_breaks = "1 year")+
  theme_classic()+
    theme(plot.title = element_text(size = 15,hjust = 0.5, face = "bold"),
          axis.text.x = element_text(size = 15, face = "bold"),
          axis.text.y = element_text( size = 15, face = "bold"),
          axis.title = element_text(size = 15, face = "bold"),
          legend.text = element_text(size = 15),
          legend.title = element_text(size = 15, face = "bold"),
          legend.position = c(0.2, 0.8),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black")) 


```

