---
title: "NewListings"
output: html_document
---

```{r}
  library(Housing)
  library(ggplot2)
  library(dplyr)
  library(viridis)

ggplot(HousingMarket, aes(y = Inventory, x = New.Listings, color = Region, group = Region)) +
    geom_point(size = 1, alpha = 0.7) +
    geom_line(size = 0.5, alpha = 0.8) +
    scale_color_viridis_d(option = "C", begin = 0.1, end = 0.9) +  # Use the same color scale for the line graph
    labs(
      title = "New Listings vs. Inventory",
      x = "New Listings",
      y = "Inventory",
      color = "Region"
    ) +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))

```








```{r}

ggplot(HousingMarket, aes(y = Inventory, x = New.Listings, color = Region)) +
  geom_point(size = 1, alpha = 0.7) +
  geom_line(size = 0.5, alpha = 0.8) +
  scale_color_viridis_d(option = "E", begin = 0.1, end = 0.9) +  
  facet_wrap(~Region, scales = "fixed") +
  labs(
    title = "New Listings vs. Inventory (by Region)",
    x = "New Listings",
    y = "Inventory",
    color = "Region"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(size = 10, margin = margin(t = 5)),  # Combine size & margin
    strip.text = element_text(size = 12), 
    panel.spacing = unit(1, "lines")  # Adjust facet spacing
  )

```

```{r}
ggplot(HousingMarket, aes(y = Inventory, x = New.Listings, color = Region)) +
  geom_point(size = 1, alpha = 0.7) +
  #geom_line(size = 0.5, alpha = 0.8) +
  scale_color_viridis_d(option = "C", begin = 0.1, end = 0.9) +  
  facet_wrap(~Region, scales = "fixed") +  # Allow different x-axis scales
  labs(
    title = "New Listings vs. Inventory (by Region)",
    x = "New Listings",
    y = "Inventory",
    color = "Region"
  ) +
  theme_minimal() +
   theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(size = 10, margin = margin(t = 5)),  # Bold x-axis text
    strip.text = element_text(size = 12), 
    panel.spacing = unit(1, "lines"),
    strip.placement = "outside",  # Ensures facets are positioned properly
    legend.position = c(0.9, 0.03),  # Adjust x and y to move legend into empty space
    legend.justification = c(1, 0),
    legend.text = element_text(size = 12),  # Adjust legend text size
    legend.title = element_text(size = 15),  # Adjust legend title size
    legend.box.background = element_rect(color = "black"),
    legend.box.margin = margin(8, 10, 8, 10),  # Add space around the legend box
    #legend.key.size = unit(10000, "lines"),  # Increase the size of the legend keys
    legend.key.height = unit(2, "lines"),  # Adjust the height of the keys
    legend.key.width = unit(4, "lines")
    #axis.line = element_line(size = 0.5, color = "black")  # Increase thickness of axis lines
  )


```





